spring:
  application:
    name: discovery
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
server:
  port: 8761
logging:
  level:
    root: INFO
    jp.co.sunarch: DEBUG
  file: logs/${spring.application.name}.log
  